# Generated by Django 4.0.2 on 2024-06-10 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseasedepartmentmapping',
            old_name='department_name',
            new_name='department',
        ),
    ]
