# Generated by Django 5.0.6 on 2024-10-05 20:56

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_medicalrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecordFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='medical_records/')),
                ('mr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicalrecord')),
            ],
        ),
    ]
