# Generated by Django 5.0.6 on 2024-10-05 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_medicalrecordfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecordfiles',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 21, 0, 18, 294038, tzinfo=datetime.timezone.utc)),
        ),
    ]
