# Generated by Django 5.0.6 on 2024-10-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_medicalrecordfiles_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecordfiles',
            name='dateTime',
            field=models.DateTimeField(),
        ),
    ]
