# Generated by Django 5.0.6 on 2024-10-05 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_medicalrecordfiles_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecordfiles',
            name='dateTime',
        ),
    ]
