# Generated by Django 5.0.6 on 2024-10-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_medicalrecordfiles_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecordfiles',
            name='filename',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
