# Generated by Django 4.0.2 on 2024-06-10 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_department_name_diseasedepartmentmapping_department'),
        ('authentication', '0004_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='speciality',
        ),
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.department'),
            preserve_default=False,
        ),
    ]
